### ISSUE TITLE
Remove 'Output' string

### ISSUE THREAD

**Issue by igormcoelho** [shoeffner/pandoc-source-exec#11]
congratulations for this useful filter @shoeffner ... I've been using it a lot on https://github.com/igormcoelho/ilectures-pandoc project!

I guess 'Output' string is highly undesired... on my local file I just removed it. Do you think it's useful in any situation? If that's useful for something, maybe a flag to remove it would be quite nice.

Just to mention that my use-cases involve generating side images, that are directly embedded on pandoc output... Other issues with 'Output' is that it refers to English, but my output is not English :)

**Comment by shoeffner** [comment]
This is a good idea. I used it for an introductory class and found it might
be useful for the students if the output was "highlighted", but of course
it is not necessary nor internationalized.
I don't even know what happens if I hide the code block...
So please either submit a PR or wait until next week, I don't have time
over the weekend :)

**Comment by igormcoelho** [comment]
Thanks for the attention @shoeffner , I can propose the PR :) Congratulations again.

**Comment by igormcoelho** [comment]
Some examples (on vscode markdown-preview-enhanced):
![image](https://user-images.githubusercontent.com/290989/89716636-0a01f680-d985-11ea-8cc1-07d1972d9361.png)

Output on pdf beamer:
![image](https://user-images.githubusercontent.com/290989/89716644-1e45f380-d985-11ea-975d-ab9dd260783d.png)

Source on markdown (four options and extra slash to prevent github preview):

```md
\```{.python .exec cmd='codes/run_python3.sh'} 
print("Hello World!")
\```

\```{.python .exec cmd='codes/run_python3.sh' output_label='Saída:'} 
print("Olá Mundo! (with portuguese label)")
\```

\```{.python .exec cmd='codes/run_python3.sh' output_label=''} 
print("Hello World! (no label)")
\```

\```{.python .exec cmd='codes/run_python3.sh' output_label='' .hide} 
print("Output with source hidden and no label above")
\```
```

**Comment by igormcoelho** [comment]
Just to register my crazy `run_python3.sh` script, that makes it possible to have same behavior on vscode plugin `markdown-preview-enhanced` and this one here... maybe some day in the future, one of both could change, I don't know which hahaha
Anyway:
```sh
#!/bin/bash

#echo "Arguments: $# -> $@"

CMD=/usr/bin/python3

if [ $# -eq 0 ]; then
   echo "" # nothing to do
else
  #echo "ARG0: $0"
  #echo "ARG1: $1"
  #if [ -z "$1" ]; then echo "EMPTY"
  #fi
  #echo "ARG2: $2"
  # check if last argument is file
  if [ ! -f "${@: -1}" ]; then
    #echo "INVOKING $CMD FOR CODE: $@"
    echo "$@" | $CMD  # just 'echo' all
  elif [ -z "$1" ]; then
    #echo "EMPTY CODE! JUST RUN: $CMD ${@:2}"
    $CMD "${@:2}" # skip first empty argument
  else
    #echo "INVOKING $CMD ${@:1:$(($#-1))} FOR FILE: ${@: -1}"
    cat "${@: -1}"  | $CMD "${@:1:$(($#-1))}" # all but last
  fi
fi

#"${@:1:$(($#-1))}"
#`dirname $0`/cat_echo.sh "$@" | /usr/bin/python3
```
