### ISSUE TITLE
Avoid generating paragraphs for empty code outputs

### ISSUE THREAD

**Issue by igormcoelho** [shoeffner/pandoc-source-exec#13]
I don't know if you'll like this idea @shoeffner, but it was something I needed here...
due to some side processing in some exec tasks, I don't expect any output, but just to generate some figures (such as LaTeX pseudocodes) and then manually embed them on document.

So, for these cases, I created a `void=true` flag, that doesn't generate any output in block. I needed this, otherwise it still generated some "empty" block that occupied a little bit of blank space.
Please take your time, #11 has priority, I think it's good... this one here deserved some better solution, perhaps.
Regards

P.S.: general idea of change.
```py
                if output_label != '':
                    elems += [pf.Para(pf.Emph(pf.Str(output_label))), block]
                elif 'void' in elem.attributes:
                    # nothing to do
                    pass
                else:
                    elems += [block]
```

**Comment by igormcoelho** [comment]
Do you think it's doable to detect that block is empty (nothing injected as output) and prevent creating the block? This would be the perfect solution, in my opinion. I'll think about it. Good weekend!

**Comment by shoeffner** [comment]
It is perfectly fine to have an empty output, and indeed I just kept the small resulting block so far. 
I agree that we should change that and detect empty outputs to avoid printing that small paragraph, but I would not want to introduce an attribute for that.

I don't think writing code into a markdown file to benefit from its side-effects is a good idea. Instead, the code should be kept in a different file and invoked during the build process. For example, when I was working on my master's thesis, I simply set up a Makefile to generate certain figures:

```Makefile
figure.png:
	python3 create_figure.py --out figure.png

doc.pdf: doc.tex figure.png
	pandoc -o doc.pdf doc.md
```

Or do you think the markdown document should create its files on its own? Maybe https://github.com/jankatins/knitpy solves these problems in a better way?

**Comment by igormcoelho** [comment]
I think the automatic paragraph compression is already a good idea, for all cases (if no output is provided). Maybe I can propose that PR.
Regarding use-case, I agree it's strange... I'm using this to put LaTeX pseudo-codes on beamer. Current situation is at least feasible for practice, but far from perfect (some example on vscode).
![image](https://user-images.githubusercontent.com/290989/90020309-12f50f80-dc86-11ea-930b-416ee5320954.png)

The issue is that I'm having a double visualization, which is bad, for a single pseudocode (but only one "appears" on beamer). The reason is that I'm manually injecting a figure which is generated by side-effect...

The best solution would be to automatically put the resulting figure as output, I guess it's similar to some stuff you have for matplotlib (and some many more others from pandoc-plot filter project). Must see how to deal with output figures, instead of text.

That said, I understand that makefile solution is more than enough... but I'm still trying some more "self-contained" approach, in document itself... let's see.

**Comment by shoeffner** [comment]
Have you tried using non-code environments? In pandoc you can use inline-latex.
For example, you could do the following:

```
---
title: Algorithm example
author: Igor
header-includes:
    - \usepackage[portuguese,ruled,vlined,linesnumbered]{algorithm2e}
    - \renewcommand{\thealgocf}{}
...

## This is an interesting algorithm

\begin{algorithm}[H]
\DontPrintSemicolon
\SetAlgoLined
\SetKwInOut{Input}{Input}\SetKwInOut{Output}{Output}
\Entrada{Write here the input}
\Saida{Write here the output}
\BlankLine
\Enqto{condiçāo nāo satisfeita}{
    instructions\;
    \eSe{condition}{
        instructions1\;
        instructions2\;
    }{
        instructions3\;
    }
}
\caption{While loop with If/Else condition}
\end{algorithm}

```

which compiles fine for me using `pandoc -o algo_ex.pdf -t beamer algor_ex.md`.

Or is there a specific reason why you want to execute the latex code in a seperate process?

**Comment by igormcoelho** [comment]
Embedded LaTeX works fine for beamer output, but not for others... in my case, I generate PDF (beamer) but also HTML (reveal) for online/interactive slides.

Example:

PDF beamer
![image](https://user-images.githubusercontent.com/290989/90067680-d5b07200-dcc5-11ea-8f1b-be7b87e065f3.png)

HTML reveal
![image](https://user-images.githubusercontent.com/290989/90067616-c16c7500-dcc5-11ea-9002-afbf6c8584ab.png)

Input:


```md
## Exemplo Algo

\```{.latex .exec .hide hide=true void=true cmd='codes/run_latex.sh' args='figs/pseudo2.svg' output_label=''}
\documentclass{standalone}
\usepackage[portuguese,ruled,vlined,linesnumbered]{algorithm2e}
%
%\renewcommand{\thealgorithm}{}
\renewcommand{\thealgocf}{}  % no number on algorithm2e
%
\begin{document}
\pagestyle{empty}
%
\begin{algorithm}[H]
\DontPrintSemicolon
\SetAlgoLined
%\KwResult{Write here the result}
\SetKwInOut{Input}{Input}\SetKwInOut{Output}{Output}
\Entrada{Write here the input}
\Saida{Write here the output}
\BlankLine
\Enqto{condição não satisfeita}{
    instructions\;
    \eSe{condition}{
        instructions1\;
        instructions2\;
    }{
        instructions3\;
    }
}
\caption{While loop with If/Else condition}
\end{algorithm} 
\end{document}
\```
![Test Algorithm](./figs/pseudo2.svg){width=70%}
```

With the "undesired" extra (which some slight changes here in this filter may help avoid completely):
`![Test Algorithm](./figs/pseudo2.svg){width=70%}`

**Comment by shoeffner** [comment]
Okay, that is indeed something I haven't thought about yet.

I think your solution is quite elegant with the "undesired" extra, because it prevents the code environment from also taking all the arguments the figure would take. But I agree that for that, at least the (empty) output needs to be left out.

Indeed, I would go as far as removing the matplotlib functionality again and always recommend this style to generate figures as it seems much cleaner.

*NB: Why does it need `.hide hide=true`, that's interesting – isn't one of both enough?*

**Comment by igormcoelho** [comment]
hahah you see the challenges... `.hide hide=true` is one of them. `pandoc-source-exec` requires `.hide`, and with `hide=true` it doesn't hide.
![image](https://user-images.githubusercontent.com/290989/90208350-07593400-ddbf-11ea-963e-4bdadede00e5.png)

On the other hand, `markdown-preview-enhanced` plugin for vscode/atom only hides with `hide=true`, and doesn't hide with `.hide`...
![image](https://user-images.githubusercontent.com/290989/90208437-3a9bc300-ddbf-11ea-824c-27ef98c1db43.png)

So, since the beggining, `pandoc-source-exec` filter was "standard pandoc filter" to me, and I had to make it compatible with the preview plugin on vscode... now that I can talk to the "owner", it would be very helpful if both sintaxes are somehow accepted :) (so that I would only use `hide=true`... or maybe talk to the "other guy" in markdown plugin for him to accept both too xD).

**Comment by shoeffner** [comment]
`hide=true` is now accepted. However, I think .hide is a cleaner solution (especially when it comes to HTML output and the like, as one can then write css such as `.hide {display: none}` instead of `*[hide="true"] {display: none}`). Thus, I built it so that `attribute=true` adds the class `.attribute`.
