### ISSUE TITLE
pip:    SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by jvw1954** [shoeffner/pandoc-source-exec#2]
jaap@jaap:/$ pip install pandoc-source-exec
Collecting pandoc-source-exec
  Downloading pandoc-source-exec-0.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-klFzZx/pandoc-source-exec/setup.py", line 7, in <module>
        from pandoc_source_exec import __version__
      File "pandoc_source_exec.py", line 197
        print(tikz)"""
                     ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-klFzZx/pandoc-source-exec/
jaap@jaap:/$

**Comment by shoeffner** [comment]
Which Python version are you using? With 3.6 I don't have any troubles, but that line is a multiline formatted string literal, which is not supported in versions < 3.6.

**Comment by shoeffner** [comment]
Do you have any updates on this?

**Comment by shoeffner** [comment]
Closed as inactive.
